# Generated by Django 2.2.1 on 2019-05-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadGraph',
            new_name='DssFiles',
        ),
    ]
