# Generated by Django 2.2.1 on 2019-05-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190521_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dssfiles',
            name='path',
            field=models.FilePathField(match='<django.db.models.fields.CharField>.dss', path='/Users/yeungSL/Desktop/Replan_API/Replan_api_v1/api/files', recursive=True),
        ),
    ]
