# Generated by Django 2.2.1 on 2019-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190521_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dssfiles',
            name='path',
            field=models.FilePathField(path='/Users/yeungSL/Desktop/Replan_API/Replan_api_v1/api/files/'),
        ),
    ]
