# Generated by Django 2.2.1 on 2019-05-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190521_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dssfiles',
            name='path',
        ),
    ]
