# Generated by Django 2.2.1 on 2019-05-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dssfiles_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dssfiles',
            name='path',
            field=models.FilePathField(default='Some String', path='/Users/yeungSL/Desktop/Replan_API/Replan_api_v1/api/files'),
        ),
    ]
