# Generated by Django 2.2.1 on 2019-05-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dssfiles_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dssfiles',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
